name = "DiefAlpha Pack 2024"
author = "DieAlpha"
version = "4.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbcb7e50b90f17d3e752aae4d17c31efb52b46d6ae1a35e7ee5b99352ec6ba71"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
