name = "DiefAlpha MCPack"
author = "DieAlpha"
version = "1.20.1-1.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3acfd1c287bbd11b6251a63e7a317a40a72321b30074cf52b9caa66766cf94f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
