name = "DiefAlpha MCPack"
author = "DieAlpha"
version = "1.20.1-1.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66b67d9f5edd669ec7bcb767c1b92819b60df34936ed149d823f0fb57ec92481"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
